spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GaviotaBBDD
    username: UserGaviota
    password: Gaviota_DSS2024
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
